version: "3.8"

services:
  db:
    image: postgres:15  # 你可以选择使用 postgres:15 或 postgres:latest
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql  # 挂载到 /var/lib/postgresql 而不是 /data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marksuser", "-d", "marksdb"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_USER: marksuser
      DB_PASSWORD: markspass
      DB_NAME: marksdb
    ports:
      - "5001:5001"  # 后端端口
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5001 app:app  # 启动后端服务

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"  # 前端端口
    depends_on:
      - backend  # 确保后端服务先启动

  automark:  # automark 服务
    build: ./automark
    depends_on:
      - backend
      - db
    profiles:
      - debug

volumes:
  db-data:
