version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: marksuser
      POSTGRES_PASSWORD: markspass
      POSTGRES_DB: marksdb
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql  # 挂载到 /var/lib/postgresql 而不是 /data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "marksuser", "-d", "marksdb"]
      interval: 30s
      retries: 5
      start_period: 10s
      timeout: 10s

  backend:
    build: ./backend  # 后端代码路径
    environment:
      DB_HOST: db
      DB_USER: marksuser
      DB_PASSWORD: markspass
      DB_NAME: marksdb
    ports:
      - "5001:5001"  # 将容器的 5001 端口映射到主机的 5001 端口
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5001 app:app  # 启动后端服务

  frontend:
    build: ./frontend  # 前端代码路径
    ports:
      - "8080:8080"  # 前端运行在 8080 端口
    depends_on:
      - backend  # 确保后端服务先启动
  automark:  # 添加 automark 服务
    image: liosu/automark
    container_name: automark
    ports:
      - "9900:9900"
    depends_on:
      - db
    # 更多配置项


volumes:
  db-data:
